name: LiteStat
options:
  bundleIdPrefix: online.wuhundian
  deploymentTarget:
    macOS: '12.0'
targets:
  LiteStat:
    type: application
    platform: macOS
    sources:
      - path: Sources
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: online.wuhundian.litestat
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: 5.9
        ENABLE_DEBUG_DYLIB: NO
    dependencies:
      - sdk: IOKit.framework
      - sdk: Metal.framework
